import { Injectable, NotFoundException } from "@nestjs/common";
import { User } from "./entities/user.entity";
import { CreateUserDto } from "./dto/create-user.dto";
import { UpdateUserDto } from "./dto/update-user.dto";
import { UserRepository } from "./repositories/user.repository";

@Injectable()
export class UsersService {
  constructor(private readonly userRepository: UserRepository) {}

  /**
   * Create a new user
   * UUID is automatically generated by TypeORM
   * Example: id will be "550e8400-e29b-41d4-a716-446655440000"
   */
  async create(createUserDto: CreateUserDto): Promise<User> {
    // Check if email already exists
    const emailExists = await this.userRepository.emailExists(
      createUserDto.email,
    );
    if (emailExists) {
      throw new NotFoundException(
        `User with email ${createUserDto.email} already exists`,
      );
    }

    const savedUser = await this.userRepository.create(createUserDto);

    // savedUser.id will be a UUID string like: "550e8400-e29b-41d4-a716-446655440000"
    console.log("Created user with UUID:", savedUser.id);

    return savedUser;
  }

  /**
   * Find all users
   * Returns array of users with UUID ids
   */
  async findAll(): Promise<User[]> {
    return this.userRepository.findAll();
  }

  /**
   * Find user by UUID
   * UUID format: "550e8400-e29b-41d4-a716-446655440000"
   */
  async findOne(id: string): Promise<User> {
    const user = await this.userRepository.findOne(id);

    if (!user) {
      throw new NotFoundException(`User with UUID ${id} not found`);
    }

    return user;
  }

  /**
   * Update user by UUID
   */
  async update(id: string, updateUserDto: UpdateUserDto): Promise<User> {
    return this.userRepository.update(id, updateUserDto);
  }

  /**
   * Delete user by UUID
   */
  async remove(id: string): Promise<void> {
    return this.userRepository.remove(id);
  }

  /**
   * Find user by email
   */
  async findByEmail(email: string): Promise<User | null> {
    return this.userRepository.findByEmail(email);
  }

  /**
   * Find users by admin status
   */
  async findByAdminStatus(isAdmin: boolean): Promise<User[]> {
    return this.userRepository.findByAdminStatus(isAdmin);
  }

  /**
   * Find users by guest status
   */
  async findByGuestStatus(isGuest: boolean): Promise<User[]> {
    return this.userRepository.findByGuestStatus(isGuest);
  }
}
