import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { User } from './entities/user.entity';
import { CreateUserDto } from './dto/create-user.dto';
import { UpdateUserDto } from './dto/update-user.dto';

@Injectable()
export class UsersService {
  constructor(
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
  ) {}

  /**
   * Create a new user
   * UUID is automatically generated by TypeORM
   * Example: id will be "550e8400-e29b-41d4-a716-446655440000"
   */
  async create(createUserDto: CreateUserDto): Promise<User> {
    const user = this.userRepository.create(createUserDto);
    const savedUser = await this.userRepository.save(user);
    
    // savedUser.id will be a UUID string like: "550e8400-e29b-41d4-a716-446655440000"
    console.log('Created user with UUID:', savedUser.id);
    
    return savedUser;
  }

  /**
   * Find all users
   * Returns array of users with UUID ids
   */
  async findAll(): Promise<User[]> {
    return this.userRepository.find();
  }

  /**
   * Find user by UUID
   * UUID format: "550e8400-e29b-41d4-a716-446655440000"
   */
  async findOne(id: string): Promise<User> {
    const user = await this.userRepository.findOne({ where: { id } });
    
    if (!user) {
      throw new NotFoundException(`User with UUID ${id} not found`);
    }
    
    return user;
  }

  /**
   * Update user by UUID
   */
  async update(id: string, updateUserDto: UpdateUserDto): Promise<User> {
    const user = await this.findOne(id); // This will throw if not found
    
    Object.assign(user, updateUserDto);
    return this.userRepository.save(user);
  }

  /**
   * Delete user by UUID
   */
  async remove(id: string): Promise<void> {
    const user = await this.findOne(id); // This will throw if not found
    await this.userRepository.remove(user);
  }

  /**
   * Find user by email (example of using other fields)
   */
  async findByEmail(email: string): Promise<User | null> {
    return this.userRepository.findOne({ where: { email } });
  }
}
